version: '3.8'
services:
  api:
    build: .
    ports:
      - 8080:8080
    restart: always
    volumes:
      - .env:/app/.env
    depends_on:
          db:
            condition: service_healthy
  db:
    image: mysql:8.0
    container_name: faceit-db-host
    restart: always
    environment:
      MYSQL_DATABASE: 'faceit'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'faceituser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'faceittestpassword'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'faceittestpassword'
    ports:
      - '3306:3306'
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
